### ISSUE TITLE
Navigation items point to the wrong page

### ISSUE THREAD

**Issue by benjackwhite** [gridscale/terraform-provider-gridscale#68] opened 2020-04-03 16:43 UTC
Note: This issue is possibly the same as https://github.com/terraform-providers/terraform-provider-gridscale/issues/57 and is closed but does not seem to be reflected on the terraform docs?

### Terraform Version
N/A (on the website documentation)

### Affected Resource(s)
Please list the resources as a list, for example:
- gridscale_paas
- gridscale_paas_securityzone

### Expected Behavior

- Clicking `gridscale_paas` on the navigation sidebar should link to https://www.terraform.io/docs/providers/gridscale/d/paas.html
- Clicking `gridscale_paas_securityzone` on the navigation sidebar should link to https://www.terraform.io/docs/providers/gridscale/d/securityzone.html

### Actual Behavior
For both data and resource sections it is the wrong way around:

- Clicking `gridscale_paas` on the navigation sidebar should link to https://www.terraform.io/docs/providers/gridscale/d/securityzone.html
- Clicking `gridscale_paas_securityzone` on the navigation sidebar should link to https://www.terraform.io/docs/providers/gridscale/d/paas.html

### Steps to Reproduce
1. Go to https://www.terraform.io/docs/providers/gridscale/d/securityzone.html
2. Click on the relevant sidebar items mentioned above

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
https://github.com/terraform-providers/terraform-provider-gridscale/pull/67 is working on the sidebar so may have found a similar issue?

**Comment by sharkwouter** [comment] 2020-04-03 16:56
I hadn't noticed this, but I do see where the problem is. Should I add a commit which fixes it to the pull request?

**Comment by bkircher** [comment] 2020-04-06 05:19
Already fixed on current master in 3eaf52b44ab4a6a2297fc83aa9f70cfad1dfb806. We need to push another update.

**Closed as completed** 2020-04-06 20:11 UTC
Labels: documentation
